import type { Game } from '../types';

export const PRESET_GAMES: Game[] = [
  { id: 'preset-catan', name: 'カタン', genres: ['strategy', 'negotiation'], isPreset: true, createdAt: '' },
  { id: 'preset-dominion', name: 'ドミニオン', genres: ['strategy'], isPreset: true, createdAt: '' },
  { id: 'preset-codenames', name: 'コードネーム', genres: ['memory', 'cooperative'], isPreset: true, createdAt: '' },
  { id: 'preset-bang', name: 'バング！', genres: ['luck', 'negotiation'], isPreset: true, createdAt: '' },
  { id: 'preset-pandemic', name: 'パンデミック', genres: ['cooperative', 'strategy'], isPreset: true, createdAt: '' },
  { id: 'preset-hanabi', name: 'ハナビ', genres: ['cooperative', 'memory'], isPreset: true, createdAt: '' },
  { id: 'preset-7wonders', name: '7 Wonders', genres: ['strategy'], isPreset: true, createdAt: '' },
  { id: 'preset-love-letter', name: 'ラブレター', genres: ['luck', 'memory'], isPreset: true, createdAt: '' },
  { id: 'preset-dixit', name: 'ディクシット', genres: ['luck', 'memory'], isPreset: true, createdAt: '' },
  { id: 'preset-werewolf',          name: '人狼',                     genres: ['negotiation'],                isPreset: true, createdAt: '' },
  { id: 'preset-carcassonne',       name: 'カルカソンヌ',             genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-ticket-to-ride',    name: 'チケット・トゥ・ライド',   genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-terraforming-mars', name: 'テラフォーミング・マーズ', genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-azul',              name: 'アズール',                 genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-splendor',          name: '宝石の煌き / Splendor',    genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-skull',             name: 'スカル',                   genres: ['luck', 'negotiation'],        isPreset: true, createdAt: '' },
  { id: 'preset-blokus',            name: 'ブロックス',               genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-kingdomino',        name: 'キングドミノ',             genres: ['strategy', 'luck'],           isPreset: true, createdAt: '' },
  { id: 'preset-wingspan',          name: 'ウイングスパン',           genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-timebomb',          name: 'タイムボム',               genres: ['cooperative', 'negotiation'], isPreset: true, createdAt: '' },
  { id: 'preset-cockroach-poker',   name: 'ごきぶりポーカー',         genres: ['luck', 'negotiation'],        isPreset: true, createdAt: '' },
  { id: 'preset-coyote',            name: 'コヨーテ',                 genres: ['luck', 'negotiation'],        isPreset: true, createdAt: '' },
  { id: 'preset-nanjamo',           name: 'ナンジャモンジャ',         genres: ['memory', 'luck'],             isPreset: true, createdAt: '' },
  { id: 'preset-geistesblitz',      name: 'おばけキャッチ',           genres: ['memory'],                     isPreset: true, createdAt: '' },
  { id: 'preset-avalon',            name: 'レジスタンス：アヴァロン', genres: ['negotiation'],                isPreset: true, createdAt: '' },
  { id: 'preset-secret-hitler',     name: 'シークレットヒトラー',     genres: ['negotiation'],                isPreset: true, createdAt: '' },
  { id: 'preset-everdell',          name: 'エバーデール',             genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-istanbul',          name: 'イスタンブール',           genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-odin',              name: 'オーディンの祝祭',         genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-patchwork',         name: 'パッチワーク',             genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-6nimmt',           name: 'ニムト（6 nimmt!）',       genres: ['luck', 'strategy'],           isPreset: true, createdAt: '' },
  { id: 'preset-cascadia',         name: 'カスカディア',             genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-komplett',         name: 'コンプレット',             genres: ['strategy', 'luck'],           isPreset: true, createdAt: '' },
  { id: 'preset-5cucumbers',       name: '5本のきゅうり',           genres: ['luck', 'strategy'],           isPreset: true, createdAt: '' },
  { id: 'preset-machikoro',        name: '街コロ',                   genres: ['strategy', 'luck'],           isPreset: true, createdAt: '' },
  { id: 'preset-tiger-dragon',     name: 'タイガー＆ドラゴン',       genres: ['strategy', 'luck'],           isPreset: true, createdAt: '' },
  { id: 'preset-citadels',         name: 'あやつり人形',             genres: ['strategy', 'negotiation'],   isPreset: true, createdAt: '' },
  { id: 'preset-ito',              name: 'ito',                      genres: ['cooperative'],                isPreset: true, createdAt: '' },
  { id: 'preset-battleline',       name: 'バトルライン',             genres: ['strategy'],                   isPreset: true, createdAt: '' },
  { id: 'preset-draftsaurus',      name: 'ドラフトサウルス',         genres: ['strategy', 'luck'],           isPreset: true, createdAt: '' },
  { id: 'preset-first-rat',        name: 'ファーストラット',         genres: ['strategy'],                   isPreset: true, createdAt: '' },
];
