export const PRESET_GAME_IMAGES: Record<string, string> = {
  // ── 既存10作品 ──
  'preset-catan':             '/game-images/catan.png',
  'preset-dominion':          '/game-images/dominion.png',
  'preset-codenames':         '/game-images/codenames.png',
  'preset-bang':              '/game-images/bang.png',
  'preset-pandemic':          '/game-images/pandemic.png',
  'preset-hanabi':            '/game-images/hanabi.png',
  'preset-7wonders':          '/game-images/7wonders.png',
  'preset-love-letter':       '/game-images/love-letter.png',
  'preset-dixit':             '/game-images/dixit.png',
  'preset-werewolf':          '/game-images/werewolf.png',
  // ── 追加20作品（画像を public/game-images/ に追加すると自動で表示されます） ──
  'preset-carcassonne':       '/game-images/carcassonne.png',
  'preset-ticket-to-ride':    '/game-images/ticket-to-ride.png',
  'preset-terraforming-mars': '/game-images/terraforming-mars.png',
  'preset-azul':              '/game-images/azul.jpg',
  'preset-splendor':          '/game-images/splendor.png',
  'preset-skull':             '/game-images/skull.png',
  'preset-blokus':            '/game-images/blokus.png',
  'preset-kingdomino':        '/game-images/kingdomino.jpg',
  'preset-wingspan':          '/game-images/wingspan.png',
  'preset-timebomb':          '/game-images/timebomb.png',
  'preset-cockroach-poker':   '/game-images/cockroach-poker.png',
  'preset-coyote':            '/game-images/coyote.png',
  'preset-nanjamo':           '/game-images/nanjamo.png',
  'preset-geistesblitz':      '/game-images/geistesblitz.png',
  'preset-avalon':            '/game-images/avalon.jpg',
  'preset-secret-hitler':     '/game-images/secret-hitler.jpg',
  'preset-everdell':          '/game-images/everdell.jpg',
  'preset-istanbul':          '/game-images/istanbul.jpg',
  'preset-odin':              '/game-images/odin.jpg',
  'preset-patchwork':         '/game-images/patchwork.png',
  'preset-6nimmt':            '/game-images/6nimmt.png',
  'preset-cascadia':          '/game-images/cascadia.png',
  'preset-komplett':          '/game-images/komplett.png',
  'preset-5cucumbers':        '/game-images/5cucumbers.jpg',
  'preset-machikoro':         '/game-images/machikoro.png',
  'preset-tiger-dragon':      '/game-images/tiger-dragon.png',
  'preset-citadels':          '/game-images/citadels.png',
  'preset-ito':               '/game-images/ito.png',
  'preset-battleline':        '/game-images/battleline.png',
  'preset-draftsaurus':       '/game-images/draftsaurus.png',
  'preset-first-rat':         '/game-images/first-rat.jpg',
};
